import json
import re

real_paragraphs = {
    # Database
    "Live Classes": "The Live Classes module actively tracks official DU SOL class schedules to ensure students never miss an important lecture. It provides direct, one-click Microsoft Teams or Zoom joining links the moment a class goes live. This centralized tracker eliminates the confusion of navigating through cluttered university portals and official WhatsApp groups.",
    "MBA in Healthcare": "This section provides highly specialized curriculum materials, case studies, and notes exclusively curated for the Hospital and Healthcare Management specialization. Students can access dedicated resources covering healthcare laws, hospital administration, and medical ethics. It serves as a focused hub for students pursuing niche medical management careers.",
    "Recorded Classes": "The Recorded Classes archive maintains an extensive video library of past university lectures and academic sessions. It allows distance education students to catch up on missed sessions or re-watch complex topics at their own pace. This ensures that no student falls behind due to working hours or scheduling conflicts.",
    "Notes": "The Notes repository delivers high-quality, unit-wise handwritten and digital notes for all core MBA subjects. These materials simplify complex management theories, financial models, and organizational behavior concepts into easy-to-understand summaries. They are perfect for daily revision and building a strong foundational understanding of the syllabus.",
    "PYQs": "Our PYQs section hosts a vast repository of Previous Year Question papers directly from past semester examinations. Reviewing these papers helps students deeply analyze university exam patterns, identify frequently recurring topics, and understand mark weightage. Practicing with real past papers is the most effective strategy for scoring high grades.",
    "One Shot Notes": "One Shot Notes provide ultra-condensed, high-yield revision materials designed specifically for last-minute exam preparation. They strip away the fluff and focus purely on the most critical formulas, definitions, and frameworks. This resource is a lifesaver for students who need a quick concept brush-up the night before an exam.",
    "E-Books": "The E-Books module grants instant access to official digital study materials, reference textbooks, and university reading lists. Students can download core reading materials directly to their devices for offline study anywhere. This completely eliminates the need to purchase expensive physical copies or wait for university mail deliveries.",
    "YouTube Videos": "This curated video section features handpicked and seamlessly embedded educational lectures from top YouTube educators. Every video is carefully mapped to the exact chapters of the DU SOL syllabus to ensure high relevance. It provides a visual and engaging alternative to traditional textbook reading for complex topics.",
    "Class Materials": "The Class Materials hub provides direct uploads of professor-provided PowerPoint presentations, PDFs, and supplementary reading files. These are the exact documents shared by educators during live academic sessions and seminars. Having access to these official slides makes it much easier to follow along with assignments and coursework.",

    # Job & Professional
    "Resume Builder": "The Resume Builder offers a streamlined way to create professional, ATS-friendly resumes using classic, minimal, and modern templates. Users simply input their academic details, work experience, and skills into an intuitive form, which automatically formats everything into a clean PDF. This eliminates the frustration of manual formatting and ensures your application passes automated corporate screening systems.",
    "Job Search": "The Job Search portal aggregates real-time active job listings and corporate openings specifically suited for MBA graduates. It filters out irrelevant postings to focus purely on management, finance, marketing, and HR roles. This saves early-career professionals hours of scrolling through generic job boards by delivering highly targeted opportunities.",
    "Career Test": "The Career Test evaluates a user's personality, core strengths, and work preferences through a series of psychological and situational questions. Based on the results, it recommends the perfect corporate career path and management specialization. It helps students who are unsure about their future confidently choose between fields like analytics, sales, or operations.",
    "Interview Preparation": "The Interview Preparation tool simulates real corporate interviews using AI to provide role-specific mock questions. Users can practice their answers in a low-pressure environment and receive strategic feedback on their communication style. This rigorous practice helps eliminate interview anxiety and drastically improves performance during real HR screening rounds.",
    "Cold Email & LinkedIn Generator": "This generator drafts highly engaging, context-aware outreach emails and LinkedIn connection requests for professional networking. It allows users to customize the tone and purpose of the message, whether reaching out to a recruiter or an alumni mentor. It takes the awkwardness out of cold messaging and significantly boosts response rates.",
    "ATS Resume Checker": "The ATS Resume Checker scans user resumes against specific job descriptions to ensure optimal keyword matching. It highlights missing skills and formatting errors that could cause a resume to be automatically rejected by Applicant Tracking Systems. By optimizing these keywords, candidates dramatically increase their chances of landing an actual interview.",
    "Cover Letter Generator": "This tool automatically writes highly tailored job application cover letters that perfectly align the applicant's skills with the job requirements. It weaves personal achievements and educational background into a compelling professional narrative. This saves applicants from the tedious process of writing a new cover letter from scratch for every single job application.",
    "Salary Calculator": "The Salary Calculator breaks down gross pay, standard taxation, and mandatory deductions to calculate the exact take-home salary. It helps students fully understand complex corporate compensation structures, including provident funds and bonuses. This clarity is crucial when negotiating job offers and planning personal finances.",
    "LinkedIn Suite": "The LinkedIn Suite provides a comprehensive checklist and automated tools to fully optimize a professional LinkedIn profile. It offers actionable advice on writing a strong headline, detailing work experience, and utilizing SEO keywords. A fully optimized profile acts as a passive resume, attracting top industry recruiters directly to your inbox.",
    "Portfolio Builder (Resume to Portfolio)": "The Portfolio Builder instantly converts a standard text resume into a visually stunning, shareable digital portfolio website. It provides a dynamic space to showcase academic projects, case studies, and certifications beyond just a piece of paper. This modern approach helps candidates stand out in competitive fields like marketing and product management.",
    "Notice Period Calculator": "This calculator determines your exact final working day based on your resignation date and standard corporate notice period policies. It accounts for weekends and public holidays to provide a precise timeline for your transition. This tool is essential for coordinating start dates with new employers and ensuring a smooth corporate exit.",
    "Corporate Translator": "The Corporate Translator translates casual, everyday language into polished, polite, and professional corporate terminology. If a user types a frustrated or overly casual message, the AI rewrites it into a diplomatic, workplace-appropriate email. This helps young professionals maintain a flawless professional image in corporate communications.",
    "Resignation & Handover": "The Resignation & Handover kit supplies professional templates for resignation letters and detailed transition checklists. It guides employees on how to document their daily tasks and hand over projects to their successors seamlessly. Leaving a company gracefully ensures that you maintain strong professional relationships and secure positive references.",
    "Freelance Rate Calculator": "The Freelance Rate Calculator helps gig workers and independent consultants calculate their optimal hourly billing rates. By factoring in personal living expenses, business costs, and target income goals, it provides a mathematically sound pricing strategy. This prevents freelancers from undervaluing their work and ensures financial stability.",
    "AI Excuse Generator": "The AI Excuse Generator crafts polite, professional, and highly believable absence or delay excuses for high-stakes environments. Whether you need a reason for a missed meeting or a delayed assignment, it provides workplace-appropriate phrasing. This helps users navigate awkward situations while maintaining a professional and responsible image.",

    # Academic & Productivity
    "Exam Prep AI": "Exam Prep AI acts as a virtual tutor, analyzing syllabus structures to predict exam topics and testing knowledge on core academic subjects. It dynamically generates practice questions based on the areas where the student is weakest. This targeted approach to studying drastically reduces preparation time and boosts final exam scores.",
    "AI Study Companion": "The AI Study Companion provides personalized assistance by breaking down complex textbook concepts into simpler, digestible explanations. Students can ask questions about difficult financial formulas or management theories and receive instant, easy-to-understand answers. It acts as an always-available mentor for distance learners who don't have direct access to professors.",
    "Smart Flashcards": "Smart Flashcards generate interactive, digital cards for active recall study sessions, drastically improving memory retention of key management terms. Users can flip through definitions, dates, and formulas, with the system repeating cards they struggle with. This scientifically proven study method is highly effective for memorizing vast amounts of syllabus data.",
    "Study Planner": "The Study Planner builds a highly structured and personalized daily study calendar based on a student's exam dates and syllabus size. It breaks down massive textbooks into manageable daily reading goals to prevent last-minute cramming. Following this automated schedule ensures that the entire curriculum is systematically covered before the finals.",
    "AI MCQ Generator": "The AI MCQ Generator automatically creates Multiple Choice Questions from raw textbook text or copied lecture notes. It allows students to rigorously self-test their comprehension immediately after reading a chapter. This instant feedback loop helps identify knowledge gaps and reinforces the material learned.",
    "AI Question Paper Generator": "This generator compiles full mock examination papers based on historical DU SOL PYQ data and syllabus weightage. It perfectly mimics the format, difficulty, and structure of the real university finals. Practicing under these simulated exam conditions drastically improves time management and reduces test anxiety.",
    "Zero Size PDF Converter": "The Zero Size PDF Converter generates empty, 0-byte placeholder PDF files instantly. This niche tool is incredibly useful for testing assignment portal upload limits, system integrations, or bypassing mandatory file uploads during portal registrations. It saves developers and students the hassle of finding or creating dummy files manually.",
    "Academic Calculator": "The Academic Calculator provides a fast, accessible standard web interface for quick arithmetic operations and statistical calculations. It remains easily accessible during online study sessions without needing to open separate desktop applications. This simple utility streamlines homework and quantitative problem-solving.",
    "Cover Page Generator": "The Cover Page Generator designs perfectly formatted front cover pages for DU SOL academic assignments. It ensures that student details, enrollment numbers, and course codes are neatly aligned according to strict university submission guidelines. This gives every assignment a professional, polished look right from the very first page.",
    "PDF/Image Converter": "This Converter seamlessly transforms digital documents between various popular image and document formats. Whether you need a PNG from a Word document or a JPEG from a PDF, it acts as a universal file utility. It ensures that students can always meet the specific file format requirements of different submission portals.",
    "PDF/Image Compressor": "The Compressor significantly reduces the file size of heavy documents and high-resolution scanned images. It optimizes these files for faster web sharing and ensures they fit within the strict megabyte limits of university assignment portals. Crucially, it achieves this size reduction without sacrificing visual quality or readability.",
    "Attendance Calculator": "The Attendance Calculator mathematically tracks exactly how many classes a student can afford to miss while maintaining required percentages. Students input their current attended and total classes to instantly see their margin of error. This helps balance academic responsibilities with internships and personal commitments without risking academic penalties.",
    "Assignment Tracker": "The Assignment Tracker monitors upcoming university assignment deadlines, submission statuses, and grading criteria in one dashboard. It sends timely reminders to ensure students never miss a critical due date or lose marks for late submissions. Keeping all coursework organized in one place drastically reduces academic stress.",
    "Web Teleprompter": "The Web Teleprompter provides a smooth, scrolling text reader designed to help students deliver flawless video presentations. Users can paste their speech scripts and adjust the scrolling speed to match their natural talking pace. This ensures virtual academic pitches and online vivas are delivered confidently without breaking eye contact with the camera.",
    "Text Humanizer": "The Text Humanizer refines AI-generated text to sound much more natural, engaging, and human-like. It removes robotic phrasing, repetitive sentence structures, and predictable vocabulary from drafts. This ensures that academic assignments and essays read authentically and pass standard AI detection filters.",

    # PDF Tools Suite
    "Merge PDF": "The Merge PDF tool effortlessly combines multiple separate PDF assignments or reading materials into a single, highly organized document. It allows users to drag and drop files into the exact order they need before stitching them together. This is essential for combining title pages, main content, and appendices into one final submission file.",
    "Split PDF": "The Split PDF tool extracts specific chapters, units, or page ranges from massive university e-books and textbooks. It splits them into smaller, manageable PDF files that are much easier to read and share. This prevents students from having to navigate through thousand-page documents just to find one specific chapter.",
    "ZIP Converter": "The ZIP Converter bundles multiple heavy study materials, project files, and assignments into a single compressed ZIP archive. This makes it incredibly easy to share large amounts of data via email or upload them as a single package to a portal. It streamlines digital file management and keeps related documents neatly grouped together.",
    "Compress PDF": "The Compress PDF tool reduces the file size of large PDF documents for easier uploading to university assignment portals. It uses advanced compression algorithms to shrink the file footprint while perfectly preserving text and image quality. This is a must-have for students dealing with strict 10MB or 5MB upload limits.",
    "PDF to Word": "PDF to Word transforms locked PDF documents into fully editable Microsoft Word files. It intelligently preserves the original layout, formatting, and fonts, allowing students to seamlessly modify and update existing text. This is incredibly useful for editing templates, updating resumes, or extracting text from research papers.",
    "PDF to PowerPoint": "This tool converts static PDF study materials and business reports into fully editable PowerPoint presentation slides. It automatically detects slides within the PDF and maps them to individual PPTX slides. This saves students hours of manually copying and pasting information when preparing for academic seminars.",
    "Word to PDF": "Word to PDF converts editable Word assignments into final, locked PDF formats to perfectly preserve formatting. This ensures that margins, fonts, and images look exactly the same on the professor's computer as they do on the student's. Submitting assignments as PDFs is the gold standard for preventing accidental document alterations.",
    "Excel to PDF": "Excel to PDF converts complex Excel spreadsheets, financial models, and data tables into secure, easily shareable PDF documents. It locks in the cell formatting and prevents formulas from being accidentally modified by viewers. This is highly useful for submitting final financial accounting assignments and corporate data reports.",
    "PDF to JPG": "PDF to JPG extracts specific pages from a PDF document and converts them into individual high-quality JPG images. This allows students to easily insert specific charts, diagrams, or pages into presentations or share them on social media. It bridges the gap between document reading and visual media sharing.",
    "JPG to PDF": "JPG to PDF compiles individual JPG images of scanned handwritten notes or textbook photos into a single, cohesive PDF document. Users can easily arrange the images in the correct chronological order before generating the final file. This creates a neat, professional document ready for university submission.",
    "Watermark": "The Watermark tool applies custom text or transparent images across the pages of a PDF document. It protects original handwritten notes, research, and assignments from unauthorized copying or plagiarism. By stamping their name or ID on a document, students can safely share their hard work with peers.",
    "Rotate PDF": "Rotate PDF easily corrects the orientation of improperly scanned PDF pages. It allows users to flip upside-down or sideways documents back to their normal upright position with a single click. This quick fix ensures that study materials are comfortable to read on laptops and mobile devices.",
    "HTML to PDF": "HTML to PDF captures entire web pages and online research articles, converting them directly into static PDF formats. It perfectly preserves the web page's layout, text, and images for offline reading and archiving. This is a fantastic way to save online sources and references permanently before they change or disappear.",
    "Unlock PDF": "Unlock PDF removes password restrictions and editing locks from protected study materials and e-books. It grants students full access to print, copy, and highlight the document's contents for their personal study. This eliminates the frustration of being locked out of essential university reading materials.",
    "Protect PDF": "Protect PDF secures personal files and sensitive academic assignments by adding robust password encryption. It prevents unauthorized users from opening, editing, or copying the contents of the document. This ensures absolute privacy for confidential research data and personal corporate documents.",
    "Organize PDF": "Organize PDF provides a visual interface that enables users to easily reorder, drag, and drop pages within a PDF file. It also allows for the quick deletion of specific pages to clean up a document. This is perfect for fixing incorrectly scanned study materials and structuring assignments logically.",
    "Page Numbers": "The Page Numbers tool automatically stamps sequential page numbers onto the corners or footers of PDF assignments. It ensures strict compliance with university formatting guidelines for lengthy reports and dissertations. This completely eliminates the tedious manual process of numbering pages one by one.",
    "Scan to PDF": "Scan to PDF acts as a virtual scanning utility for digitizing physical documents using a device's camera. It automatically detects document edges, enhances text contrast, and converts the photos into clean, highly readable digital PDF formats. It essentially puts a high-quality flatbed scanner right in a student's pocket.",
    "OCR PDF": "The OCR PDF tool uses advanced Optical Character Recognition to extract editable, searchable text from scanned images or flattened PDFs. It transforms photos of physical handwritten notes or textbook pages into digital text that can be copied and pasted. This drastically speeds up note-taking and digital archiving.",
    "AI Summarizer": "The AI Summarizer automatically condenses lengthy research papers, case studies, and textbooks into short, digestible summaries. It uses advanced AI to extract only the most critical arguments, data points, and conclusions. This tool saves students hours of reading time while ensuring they grasp the core concepts of heavy academic texts.",
    "Translate PDF": "Translate PDF automatically translates the text within a document across multiple languages while preserving the original layout. It heavily aids students studying international business case studies or foreign research papers. This breaks down language barriers and opens up a global library of academic resources.",
    "Delete PDF Pages": "Delete PDF Pages allows users to quickly remove unwanted, blank, or irrelevant pages from lengthy PDF study materials. It slims down downloaded university e-books to only the chapters actually needed for an exam. This makes documents much easier to navigate and significantly reduces file size.",
    "Add PDF Pages": "Add PDF Pages allows users to seamlessly insert blank sheets or additional document pages anywhere within an existing PDF file. This is highly useful for adding newly written content, appendices, or cover pages to an already finalized document. It provides immense flexibility in editing locked PDF files.",
    "Favicon Generator": "The Favicon Generator creates perfectly sized, multi-format website icons from uploaded images. It is incredibly useful for IT, digital marketing, and web development projects where professional branding is required. It automatically handles all the complex resizing requirements for different browsers and devices.",

    # Business & Finance
    "AI Business Validator": "The AI Business Validator evaluates the viability of startup ideas based on market parameters, competitor analysis, and financial projections. It provides entrepreneurship students with a reality check on their business models by identifying potential market risks. This data-driven feedback is crucial for building robust business pitches and feasibility reports.",
    "GST Invoice Calculator": "The GST Invoice Calculator accurately determines Goods and Services Tax amounts for various complex Indian taxation scenarios. It simplifies accounting case studies by instantly calculating CGST, SGST, and IGST breakdowns for any base amount. This tool is indispensable for finance students dealing with modern taxation assignments.",
    "SWOT Analysis Maker": "The SWOT Analysis Maker generates structured matrices identifying critical Strengths, Weaknesses, Opportunities, and Threats. It provides a clean, professional template for students to quickly map out strategic business environments. This is a foundational tool for solving marketing case studies and strategic management assignments.",
    "Business Case Template": "The Business Case Template builds structured, logical outlines for analyzing corporate dilemmas and case studies. It heavily assists students in formatting their management reports with proper executive summaries, problem statements, and proposed solutions. Following this industry-standard structure ensures high grades on MBA submissions.",
    "Financial Ratio Calculator": "The Financial Ratio Calculator instantly computes key metrics like Return on Investment (ROI), Return on Equity (ROE), and liquidity ratios. It automates the tedious math required for solving complex corporate accounting and balance sheet assignments. This allows finance students to focus on analyzing the data rather than crunching the numbers.",
    "Break-Even Calculator": "The Break-Even Calculator determines the exact point at which a business's revenue completely equals its fixed and variable costs. It generates clear visualizations and precise data points for pricing strategy and cost accounting modules. This is a crucial tool for understanding startup profitability and operational efficiency.",
    "PESTLE Analysis Maker": "The PESTLE Analysis Maker instantly generates strategic matrices to evaluate Political, Economic, Social, Technological, Legal, and Environmental factors. It helps students comprehensively analyze macro-environmental market conditions for corporate strategy modules. This broad strategic view is essential for international business assignments.",
    "Startup Valuation": "The Startup Valuation tool provides standard analytical frameworks to evaluate the financial worth and equity of early-stage business models. It uses methods like Discounted Cash Flow and comparative analysis to give entrepreneurship students realistic financial estimates. It bridges the gap between theoretical finance and practical venture capital negotiations.",
    "EMI & Loan Schedule": "The EMI & Loan Schedule tool calculates complex Equated Monthly Installments, interest amortization schedules, and total payout amounts. It provides a month-by-month breakdown of principal versus interest payments for corporate finance and banking modules. This detailed scheduling is highly practical for both academic assignments and personal financial planning.",

    # Skills
    "Personality Assessment": "The Personality Assessment conducts comprehensive psychometric evaluations to determine team fit and preferred corporate working styles. It helps students understand their intrinsic motivations and how they collaborate in professional group settings. This self-awareness is highly valuable for leadership development and organizational behavior studies.",
    "Aptitude Test": "The Aptitude Test rigorously evaluates logical, quantitative, and verbal reasoning skills under timed conditions. It perfectly mimics the competitive corporate screening rounds used by top multinational companies during campus placements. Regular practice with this tool drastically improves problem-solving speed and cognitive agility.",
    "Interest Inventory": "The Interest Inventory aligns a student's personal strengths and underlying passions with specific MBA specializations. It helps clarify whether a student is naturally suited for high-stakes finance, creative marketing, or human resource management. This guidance prevents costly career missteps and ensures long-term job satisfaction.",
    "Skill Gap Analysis": "The Skill Gap Analysis clearly identifies the missing technical or soft skills required for a student to successfully qualify for their target job profile. It compares a user's current resume against industry standards and outputs a precise list of areas needing improvement. This targeted feedback allows students to focus their learning efforts effectively.",
    "Learning Path Generator": "The Learning Path Generator delivers structured, step-by-step roadmaps for mastering highly technical industry skills. Whether learning Data Analytics, Digital Marketing, or Financial Modeling, it breaks the journey down into manageable daily milestones. This structured approach prevents students from feeling overwhelmed by massive new topics.",
    "Certification Guide": "The Certification Guide provides curated recommendations for industry-recognized certifications like CFA, PMP, or Google Analytics. It explains the cost, time commitment, and exact career benefits of each certification to boost MBA graduate employability. This helps students strategically invest in credentials that actually matter to corporate recruiters.",
    "Skill Progress Tracker": "The Skill Progress Tracker features a personal dashboard allowing students to closely monitor their growth across newly acquired competencies. Users can log their study hours, completed projects, and mastered topics over time. This visual representation of progress keeps motivation high and provides a clear record of professional development.",
    "Project Ideas Generator": "The Project Ideas Generator hosts a massive repository of highly practical, resume-building project concepts. It provides ideal topics for final semester submissions, summer internships, and professional portfolios across all MBA domains. Building these real-world projects helps students demonstrate their practical execution skills to employers.",
    "Salary Insights": "Salary Insights benchmarks current compensation expectations and industry standards across different corporate roles and geographic locations. It provides realistic data on entry-level, mid-level, and senior management salaries in various sectors. This transparency empowers students to negotiate their job offers confidently and fairly.",
    "Job Market Trends": "Job Market Trends analyzes real-time employment data, top hiring sectors, and future demand forecasting. It helps students make highly informed career choices by identifying which industries are growing and which are facing layoffs. Staying ahead of macro-economic trends is crucial for long-term career stability.",
    "Company Culture Finder": "The Company Culture Finder offers deep insights into navigating diverse corporate environments and understanding modern organizational dynamics. It reviews the work-life balance, management styles, and core values of top multinational firms. Finding a company whose culture matches your personality is key to avoiding workplace burnout.",
    "Growth Opportunities": "The Growth Opportunities module accurately maps out long-term career trajectories and standard promotion timelines across various specialized MBA domains. It shows students the exact steps needed to move from an entry-level analyst to a senior executive role. This long-term visibility helps in setting realistic and ambitious career goals.",

    # Games
    "Quiz Battle": "Quiz Battle hosts multiplayer or solo quizzes covering the entire MBA syllabus, rigorously testing a student's speed and accuracy. It gamifies the learning process by allowing students to compete against their peers on a live leaderboard. This competitive environment makes reviewing dry academic theories incredibly engaging and fun.",
    "Rapid Fire": "Rapid Fire delivers fast-paced, time-bound trivia questions explicitly designed to drastically sharpen memory recall. It challenges students to answer business and finance questions under extreme time pressure just before major examinations. This adrenaline-pumping game trains the brain to retrieve information instantly and accurately.",
    "Case Study": "The Case Study game challenges students to solve real-world corporate crises and business dilemmas in a highly interactive environment. Players are given a scenario and must make strategic decisions that impact simulated company revenue and morale. It bridges the gap between theoretical textbook knowledge and practical executive decision-making.",
    "Shark Pitch": "Shark Pitch simulates an intense entrepreneurship environment where students must craft, present, and evaluate compelling startup pitches. Players take turns acting as founders seeking investment and as venture capitalists critiquing the business models. It hones critical public speaking, financial forecasting, and negotiation skills.",
    "Market Mavericks": "Market Mavericks runs a virtual stock market and investment simulation based on real-world financial data. It allows students to test complex trading strategies, portfolio diversification, and risk management without any real financial risk. This immersive simulation is the ultimate practical training ground for future finance professionals.",

    # Core Pages
    "The Homepage": "The Homepage serves as the central dashboard for the SOLMATES platform, offering a highly intuitive, quick-access portal to all major tools. It features a clean layout that instantly directs users to their desired databases, skills, or PDF utilities. It acts as the perfect launching pad for a highly productive academic session.",
    "Notifications Page": "The Notifications Page maintains a dedicated feed for real-time announcements, ensuring students never miss urgent university updates. It aggregates deadline reminders, admit card releases, and new tool launches into one convenient timeline. Checking this page regularly guarantees that students remain fully informed about their academic responsibilities.",
    "Privacy & Terms Page": "The Privacy & Terms Page details complete information about our strict zero-data-collection policy and platform guidelines. It ensures absolute transparency regarding how user data is handled, stored, and protected during tool usage. This commitment to privacy fosters maximum user trust and a safe digital learning environment.",
    "Journey Page": "The Journey Page beautifully documents a rich timeline of the evolution, major milestones, and the ongoing educational mission behind the SOLMATES platform. It highlights the dedication of the developers and the platform's growth from a simple idea to a comprehensive educational hub. It connects users with the human story behind the technology.",
    "Feedback Page": "The Feedback Page provides an interactive portal for students to submit feature requests, report critical bugs, and share user experiences. It creates a direct line of communication between the student community and the platform developers. This continuous feedback loop ensures that SOLMATES constantly evolves to meet actual user needs.",
    "AI Chatbot": "The AI Chatbot acts as a 24/7 virtual study assistant powered by advanced Natural Language Processing. It is always ready to explain complex financial theories, summarize lengthy documents, or guide users to the correct platform tools. Having an instant, intelligent helper drastically reduces academic friction and learning time."
}

user_data = {
    "Database": [
        "Live Classes", "MBA in Healthcare", "Recorded Classes", "Notes", "PYQs", "One Shot Notes", "E-Books", "YouTube Videos", "Class Materials"
    ],
    "Job & Professional Tools": [
        "Resume Builder", "Job Search", "Career Test", "Interview Preparation", "Cold Email & LinkedIn Generator", "ATS Resume Checker", "Cover Letter Generator", "Salary Calculator", "LinkedIn Suite", "Portfolio Builder (Resume to Portfolio)", "Notice Period Calculator", "Corporate Translator", "Resignation & Handover", "Freelance Rate Calculator", "AI Excuse Generator"
    ],
    "Academic & Productivity Tools": [
        "Exam Prep AI", "AI Study Companion", "Smart Flashcards", "Study Planner", "AI MCQ Generator", "AI Question Paper Generator", "Zero Size PDF Converter", "Academic Calculator", "Cover Page Generator", "PDF/Image Converter", "PDF/Image Compressor", "Attendance Calculator", "Assignment Tracker", "Web Teleprompter", "Text Humanizer"
    ],
    "PDF Tools Suite": [
        "Merge PDF", "Split PDF", "ZIP Converter", "Compress PDF", "PDF to Word", "PDF to PowerPoint", "Word to PDF", "Excel to PDF", "PDF to JPG", "JPG to PDF", "Watermark", "Rotate PDF", "HTML to PDF", "Unlock PDF", "Protect PDF", "Organize PDF", "Page Numbers", "Scan to PDF", "OCR PDF", "AI Summarizer", "Translate PDF", "Delete PDF Pages", "Add PDF Pages", "Favicon Generator"
    ],
    "Business & Finance Tools": [
        "AI Business Validator", "GST Invoice Calculator", "SWOT Analysis Maker", "Business Case Template", "Financial Ratio Calculator", "Break-Even Calculator", "PESTLE Analysis Maker", "Startup Valuation", "EMI & Loan Schedule"
    ],
    "Skills (12 Modules)": [
        "Personality Assessment", "Aptitude Test", "Interest Inventory", "Skill Gap Analysis", "Learning Path Generator", "Certification Guide", "Skill Progress Tracker", "Project Ideas Generator", "Salary Insights", "Job Market Trends", "Company Culture Finder", "Growth Opportunities"
    ],
    "Gamified Learning (5 Games)": [
        "Quiz Battle", "Rapid Fire", "Case Study", "Shark Pitch", "Market Mavericks"
    ],
    "Core Pages & Features": [
        "The Homepage", "Notifications Page", "Privacy & Terms Page", "Journey Page", "Feedback Page", "AI Chatbot"
    ]
}

html_output = ""
for category, items in user_data.items():
    html_output += f'\n    <div class="guide-category">\n      <div class="guide-category-header">\n        <i class="fas fa-check-circle"></i>\n        <h2>{category}</h2>\n      </div>\n      <div class="guide-grid">\n'
    for item_name in items:
        full_desc = real_paragraphs.get(item_name, f"This section provides dedicated resources and functional utilities for {item_name}. It is designed to assist DU SOL MBA students in managing their academic and professional tasks effectively.")
        html_output += f'        <div class="guide-item-card">\n          <h3>{item_name}</h3>\n          <p>{full_desc}</p>\n        </div>\n'
    html_output += '      </div>\n    </div>\n'

new_nav = """
  <header class="top-nav" style="justify-content: center; background: #0f172a; border-bottom: 1px solid rgba(255,255,255,0.1);">
    <a href="/" class="logo" style="text-decoration: none; color: #f8fafc; font-size: 1.8rem; font-weight: 800; letter-spacing: 2px; font-family: 'Outfit', sans-serif;">SOLMATES</a>
  </header>
"""

with open(r"c:\Users\Toshiba\OneDrive\Desktop\solmates\frontend\platform-guide.html", "r", encoding="utf-8") as f:
    content = f.read()

# Replace the header and mobile overlay
match = re.search(r'<header class="top-nav">.*?(?=<div class="page-content)', content, re.DOTALL)
if match:
    content = content[:match.start()] + new_nav + "\n\n  " + content[match.end():]
    print("Replaced Header successfully.")
else:
    print("REGEX for header failed.")

# Replace the guide-container content
match_guide = re.search(r'(<div class="guide-container">).*?(</div>\n</div>)', content, re.DOTALL)
if match_guide:
    content = content[:match_guide.start(1)] + '<div class="guide-container">\n' + html_output + '  </div>\n</div>' + content[match_guide.end(2):]
    print("Replaced Content successfully.")
else:
    print("REGEX for guide-container failed.")

with open(r"c:\Users\Toshiba\OneDrive\Desktop\solmates\frontend\platform-guide.html", "w", encoding="utf-8") as f:
    f.write(content)
