module.exports = {
    "Organisational Behavior": [
        { q: "Which leadership style involves employees in decision-making?", options: ["Autocratic", "Democratic/Participative", "Laissez-faire", "Transactional"], a: 1 },
        { q: "In Johari Window, what is known to self but not to others?", options: ["Open Area", "Blind Area", "Hidden Area", "Unknown Area"], a: 2 },
        { q: "Which is a hygiene factor in Herzberg's theory?", options: ["Recognition", "Responsibility", "Salary", "Advancement"], a: 2 },
        { q: "Group norms are:", options: ["Written company rules", "Unspoken rules of behavior in a group", "Government laws", "Union guidelines"], a: 1 },
        { q: "A 'Grapevine' is a form of:", options: ["Formal communication", "Written communication", "Informal communication", "External communication"], a: 2 },
        { q: "What does ERG in Alderfer's theory stand for?", options: ["Existence, Relatedness, Growth", "Energy, Rewards, Goals", "Emotion, Rationality, Group", "Effort, Return, Gain"], a: 0 },
        { q: "Which defense mechanism involves attributing one's own unacceptable feelings to others?", options: ["Denial", "Rationalization", "Projection", "Regression"], a: 2 },
        { q: "In MBTI personality test, 'I' stands for:", options: ["Intuition", "Introversion", "Intelligence", "Innovation"], a: 1 },
        { q: "Eustress refers to:", options: ["Negative stress", "Positive or beneficial stress", "Chronic stress", "No stress"], a: 1 },
        { q: "The halo effect is a perceptual bias where:", options: ["People are judged based on one positive trait", "People are judged based on one negative trait", "Recent events are remembered better", "First impressions are ignored"], a: 0 },
        { q: "Which conflict handling style is low on assertiveness and high on cooperativeness?", options: ["Competing", "Avoiding", "Accommodating", "Collaborating"], a: 2 },
        { q: "Power derived from a person's specialized knowledge is:", options: ["Legitimate power", "Reward power", "Expert power", "Coercive power"], a: 2 },
        { q: "McGregor's Theory Y assumes that employees:", options: ["Are inherently lazy", "Dislike work", "Seek responsibility and enjoy work", "Must be strictly controlled"], a: 2 },
        { q: "In Lewin's Change Model, 'Refreezing' means:", options: ["Creating the need for change", "Implementing the change", "Solidifying the new behaviors", "Reverting to old habits"], a: 2 },
        { q: "An organization chart visually represents:", options: ["Financial hierarchy", "Formal structure and reporting relationships", "Customer base", "Competitor structure"], a: 1 },
        { q: "The span of control refers to:", options: ["The duration of a manager's shift", "The number of subordinates a manager can effectively direct", "The size of the office", "The budget allocated to a team"], a: 1 },
        { q: "A boundaryless organization seeks to remove:", options: ["All employees", "Vertical and horizontal boundaries", "Customer service", "Profits"], a: 1 },
        { q: "Which is a symptom of groupthink?", options: ["Seeking outside opinions", "Illusion of invulnerability", "Critical evaluation of ideas", "Encouraging dissent"], a: 1 },
        { q: "Self-efficacy is the belief in:", options: ["Others' abilities", "The company's mission", "One's own capability to perform a specific task", "Luck"], a: 2 },
        { q: "The classical conditioning experiment with dogs was conducted by:", options: ["B.F. Skinner", "Ivan Pavlov", "Sigmund Freud", "Albert Bandura"], a: 1 }
    ],
    "Data Analysis and Decision Tools": [
        { q: "A scatter plot is primarily used to:", options: ["Show frequencies", "Display the relationship between two continuous variables", "Show parts of a whole", "List qualitative data"], a: 1 },
        { q: "In a negatively skewed distribution, the mean is:", options: ["Greater than the median", "Equal to the median", "Less than the median", "Zero"], a: 2 },
        { q: "The Central Limit Theorem applies to:", options: ["Small samples only", "The distribution of sample means approaching normality as sample size increases", "Qualitative variables", "The variance of the population"], a: 1 },
        { q: "Which value represents a perfect negative correlation?", options: ["0", "1", "-1", "-100"], a: 2 },
        { q: "A Type II error is:", options: ["Rejecting a true null hypothesis", "Failing to reject a false null hypothesis", "A calculation error", "A data entry error"], a: 1 },
        { q: "Degrees of freedom for a simple linear regression (n samples) error term are:", options: ["n", "n-1", "n-2", "n-3"], a: 2 },
        { q: "The mode is defined as:", options: ["The average value", "The middle value", "The most frequently occurring value", "The difference between max and min"], a: 2 },
        { q: "A confidence interval provides:", options: ["An exact point estimate", "A range of values likely to contain the population parameter", "The standard deviation", "The correlation coefficient"], a: 1 },
        { q: "Which test compares the means of three or more independent groups?", options: ["Independent t-test", "Paired t-test", "One-way ANOVA", "Chi-square test"], a: 2 },
        { q: "Multicollinearity occurs when:", options: ["The dependent variable is categorical", "Independent variables are highly correlated with each other", "The sample size is too small", "Residuals are normally distributed"], a: 1 },
        { q: "A time series data component that repeats annually is called:", options: ["Trend", "Cyclical", "Seasonal", "Irregular"], a: 2 },
        { q: "The standard deviation is the square root of:", options: ["The mean", "The median", "The variance", "The range"], a: 2 },
        { q: "If the probability of event A is 0.4 and event B is 0.5 (mutually exclusive), P(A or B) is:", options: ["0.2", "0.9", "0.1", "0.5"], a: 1 },
        { q: "In decision theory, EMV stands for:", options: ["Estimated Market Value", "Expected Monetary Value", "Exact Mean Variance", "Error Margin Value"], a: 1 },
        { q: "A z-score of 0 indicates the value is:", options: ["An outlier", "Exactly at the mean", "Below the mean", "Above the mean"], a: 1 },
        { q: "Which of the following is a non-parametric test?", options: ["T-test", "ANOVA", "Pearson correlation", "Mann-Whitney U test"], a: 3 },
        { q: "Heteroscedasticity in regression means:", options: ["Constant variance of residuals", "Non-constant variance of residuals", "Zero correlation", "Perfect multicollinearity"], a: 1 },
        { q: "The expected value of a fair die roll is:", options: ["3", "3.5", "4", "6"], a: 1 },
        { q: "In a pie chart, the total angle is:", options: ["100 degrees", "180 degrees", "360 degrees", "400 degrees"], a: 2 },
        { q: "Data measured in categories with no inherent order (e.g. colors) is:", options: ["Nominal", "Ordinal", "Interval", "Ratio"], a: 0 }
    ],
    "Managerial Economics": [
        { q: "An isoquant curve represents:", options: ["Equal cost", "Equal utility", "Equal quantity of output from different input combinations", "Equal profit"], a: 2 },
        { q: "Economies of scale occur when long-run average cost:", options: ["Increases as output increases", "Decreases as output increases", "Remains constant", "Fluctuates"], a: 1 },
        { q: "The kinked demand curve model explains price rigidity in:", options: ["Perfect competition", "Monopoly", "Monopolistic competition", "Oligopoly"], a: 3 },
        { q: "A Giffen good is an inferior good where demand increases when:", options: ["Income rises", "Income falls", "Price rises", "Price falls"], a: 2 },
        { q: "The condition for consumer equilibrium using indifference curves is:", options: ["MRS = Ratio of prices", "MUx = MUy", "Income = Price", "TU = Maximum"], a: 0 },
        { q: "Sunk costs are:", options: ["Relevant for future decisions", "Past costs that cannot be recovered", "Variable costs", "Opportunity costs"], a: 1 },
        { q: "When Marginal Product is zero, Total Product is:", options: ["Zero", "Increasing", "Decreasing", "At its maximum"], a: 3 },
        { q: "A cartel is a formal collusive agreement most commonly found in:", options: ["Monopoly", "Oligopoly", "Perfect Competition", "Monopsony"], a: 1 },
        { q: "Implicit costs are also known as:", options: ["Accounting costs", "Opportunity costs", "Fixed costs", "Sunk costs"], a: 1 },
        { q: "If demand is perfectly elastic, the demand curve is:", options: ["Vertical", "Horizontal", "Upward sloping", "U-shaped"], a: 1 },
        { q: "The Cobb-Douglas production function exhibits constant returns to scale if the sum of exponents is:", options: ["Less than 1", "Equal to 1", "Greater than 1", "Zero"], a: 1 },
        { q: "In perfect competition, the firm's demand curve is:", options: ["Perfectly inelastic", "Perfectly elastic", "Downward sloping", "Upward sloping"], a: 1 },
        { q: "Deadweight loss occurs when:", options: ["Markets achieve perfect efficiency", "Market failure or taxes reduce total social surplus", "Profits are maximized", "Costs are minimized"], a: 1 },
        { q: "A public good is characterized by:", options: ["Rivalry and excludability", "Non-rivalry and non-excludability", "High prices", "Government ownership only"], a: 1 },
        { q: "Price elasticity of demand is calculated as:", options: ["% change in price / % change in quantity", "% change in quantity demanded / % change in price", "Change in price / Change in quantity", "Price * Quantity"], a: 1 },
        { q: "The short-run shut-down point for a competitive firm is where:", options: ["Price = Average Total Cost", "Price < Average Variable Cost", "Price = Marginal Cost", "Total Revenue = Total Cost"], a: 1 },
        { q: "Isocost lines are straight because:", options: ["Technology is constant", "Input prices are constant", "Output is constant", "Utility is constant"], a: 1 },
        { q: "Monopolistic competition involves:", options: ["A few large sellers", "One seller", "Many sellers offering differentiated products", "Many sellers offering identical products"], a: 2 },
        { q: "Cross elasticity between tea and coffee is expected to be:", options: ["Negative", "Zero", "Positive", "Infinite"], a: 2 },
        { q: "Consumer surplus is the difference between:", options: ["Total revenue and total cost", "What a consumer is willing to pay and what they actually pay", "Market price and marginal cost", "Total utility and marginal utility"], a: 1 }
    ],
    "Accounting for Managers": [
        { q: "Which statement reports cash inflows and outflows?", options: ["Balance Sheet", "Income Statement", "Cash Flow Statement", "Statement of Retained Earnings"], a: 2 },
        { q: "Prepaid expenses are classified as:", options: ["Current Liabilities", "Current Assets", "Fixed Assets", "Expenses"], a: 1 },
        { q: "The Matching Concept dictates that:", options: ["Assets must equal liabilities", "Debits must equal credits", "Expenses must be matched with the revenues they generate", "Cash inflows must match cash outflows"], a: 2 },
        { q: "Which inventory valuation method assumes the newest items are sold first?", options: ["FIFO", "LIFO", "Weighted Average", "Specific Identification"], a: 1 },
        { q: "Goodwill is classified as:", options: ["A current asset", "A tangible fixed asset", "An intangible asset", "A liability"], a: 2 },
        { q: "Double-entry bookkeeping means every transaction affects:", options: ["Only the debit side", "Only the credit side", "At least two accounts", "Only the bank account"], a: 2 },
        { q: "The Quick Ratio (Acid-Test) excludes which asset?", options: ["Cash", "Accounts Receivable", "Inventory", "Marketable Securities"], a: 2 },
        { q: "Outstanding salaries are a:", options: ["Current Asset", "Current Liability", "Fixed Asset", "Long-term Liability"], a: 1 },
        { q: "Amortization is the process of allocating the cost of:", options: ["Tangible assets", "Intangible assets", "Inventory", "Land"], a: 1 },
        { q: "Which ratio measures the efficiency of collecting receivables?", options: ["Current Ratio", "Debt-Equity Ratio", "Debtor Turnover Ratio / Receivables Turnover", "Gross Profit Ratio"], a: 2 },
        { q: "The accounting equation is based on which concept?", options: ["Going concern", "Dual aspect", "Materiality", "Conservatism"], a: 1 },
        { q: "Capital introduced by the owner is credited to:", options: ["Cash Account", "Bank Account", "Capital Account", "Drawings Account"], a: 2 },
        { q: "Which is a profitability ratio?", options: ["Current Ratio", "Quick Ratio", "Return on Equity (ROE)", "Debt Ratio"], a: 2 },
        { q: "Depreciation is calculated on:", options: ["Current assets", "Intangible assets", "Tangible fixed assets", "Fictitious assets"], a: 2 },
        { q: "A bank reconciliation statement is prepared by:", options: ["The Bank", "The Customer/Business", "The Auditor", "The Tax Authority"], a: 1 },
        { q: "Bad debts written off are recorded in the:", options: ["Trading Account", "Profit & Loss Account", "Balance Sheet", "Cash Flow Statement"], a: 1 },
        { q: "The primary purpose of an audit is to:", options: ["Calculate taxes", "Guarantee profits", "Express an opinion on the true and fair view of financial statements", "Punish fraud"], a: 2 },
        { q: "Which standard setting body issues IFRS?", options: ["FASB", "IASB", "ICAI", "SEC"], a: 1 },
        { q: "Working capital is calculated as:", options: ["Current Assets + Current Liabilities", "Fixed Assets - Current Liabilities", "Current Assets - Current Liabilities", "Total Assets - Total Liabilities"], a: 2 },
        { q: "An increase in an asset is recorded as a:", options: ["Debit", "Credit", "Loss", "Gain"], a: 0 }
    ],
    "Marketing Management": [
        { q: "In the BCG Matrix, 'Cash Cows' have:", options: ["High market share, high market growth", "Low market share, high market growth", "High market share, low market growth", "Low market share, low market growth"], a: 2 },
        { q: "Which level of a product represents the fundamental benefit the customer is buying?", options: ["Actual product", "Augmented product", "Core customer value", "Expected product"], a: 2 },
        { q: "Psychological pricing often involves setting prices ending in:", options: [".00", ".99", ".50", "Even numbers"], a: 1 },
        { q: "The promotional mix does NOT include:", options: ["Advertising", "Personal Selling", "Public Relations", "Product Design"], a: 3 },
        { q: "Exclusive distribution is commonly used for:", options: ["Convenience goods", "Shopping goods", "Specialty luxury goods", "Raw materials"], a: 2 },
        { q: "Push strategy relies heavily on:", options: ["Consumer advertising", "Personal selling and trade promotions", "Social media influencers", "Public relations"], a: 1 },
        { q: "Pull strategy is directed at:", options: ["Wholesalers", "Retailers", "Final consumers", "Competitors"], a: 2 },
        { q: "A 'Fad' is characterized by:", options: ["Slow growth and long maturity", "Rapid sales growth followed by a rapid decline", "Stable sales over decades", "Seasonal fluctuations"], a: 1 },
        { q: "Family branding involves:", options: ["Using different names for each product", "Using the same brand name for several products", "Using the founder's family name only", "Co-branding with a competitor"], a: 1 },
        { q: "Demographic segmentation divides the market based on:", options: ["Lifestyle and values", "Age, gender, income, and education", "Geographic location", "Buying behavior"], a: 1 },
        { q: "The concept of 'Marketing Myopia' was coined by:", options: ["Philip Kotler", "Theodore Levitt", "Peter Drucker", "Michael Porter"], a: 1 },
        { q: "A brand's logo, colors, and typography constitute its:", options: ["Brand equity", "Brand personality", "Brand identity", "Brand promise"], a: 2 },
        { q: "Which pricing strategy sets a low initial price to capture market share quickly?", options: ["Price skimming", "Market penetration pricing", "Value-based pricing", "Premium pricing"], a: 1 },
        { q: "A product line is a group of products that are:", options: ["Completely unrelated", "Closely related in function or target market", "Produced by different companies", "Sold only online"], a: 1 },
        { q: "The 'Place' in the 4Ps refers to:", options: ["The factory location", "Distribution channels to make the product available", "The shelf position in a store", "The target market region"], a: 1 },
        { q: "A USP is a:", options: ["Universal Standard Product", "Unique Selling Proposition", "Unit Sales Price", "Uniform Service Protocol"], a: 1 },
        { q: "Macro-environmental factors include:", options: ["Company employees", "Suppliers", "Economic, political, and technological forces", "Intermediaries"], a: 2 },
        { q: "A focus group usually consists of how many participants?", options: ["1-3", "6-10", "20-30", "100+"], a: 1 },
        { q: "Product packaging serves to:", options: ["Only protect the product", "Only provide information", "Protect, promote, and provide information", "Increase shipping costs"], a: 2 },
        { q: "Neuromarketing studies:", options: ["Competitor strategies", "Consumer brain responses to marketing stimuli", "Retail store layouts", "Pricing elasticity"], a: 1 }
    ],
    "Human Resource Management": [
        { q: "The process of forecasting HR needs is called:", options: ["Job Analysis", "HR Planning", "Performance Management", "Recruitment"], a: 1 },
        { q: "A job description focuses on:", options: ["The qualifications of the worker", "The tasks, duties, and responsibilities of the job", "The salary range", "The company history"], a: 1 },
        { q: "A job specification focuses on:", options: ["The daily tasks", "The minimum acceptable qualifications a person needs to perform the job", "The department structure", "The working hours"], a: 1 },
        { q: "Internal recruitment methods include:", options: ["Job portals", "Campus placements", "Job posting on the company intranet", "Employment agencies"], a: 2 },
        { q: "The primary purpose of an interview is to:", options: ["Test typing speed", "Assess a candidate's suitability for a role", "Check medical fitness", "Negotiate salary"], a: 1 },
        { q: "A structured interview means:", options: ["Asking completely random questions", "Asking all candidates the same predetermined questions", "Only conducting group interviews", "Interviewing outside the office"], a: 1 },
        { q: "The halo effect in an interview occurs when:", options: ["The interviewer likes everything because of one positive trait", "The candidate answers perfectly", "The room lighting is poor", "The interviewer is biased against a trait"], a: 0 },
        { q: "Orientation (Onboarding) is designed to:", options: ["Train employees on advanced software", "Introduce new employees to the organization and their jobs", "Evaluate annual performance", "Terminate employees smoothly"], a: 1 },
        { q: "In performance appraisal, the 'horn effect' is when:", options: ["One negative trait influences the overall negative rating", "The employee is too loud", "The manager is too lenient", "All employees are rated average"], a: 0 },
        { q: "Fringe benefits include:", options: ["Base salary", "Overtime pay", "Health insurance and retirement plans", "Sales commissions"], a: 2 },
        { q: "Profit-sharing is a type of:", options: ["Punishment", "Incentive compensation plan", "Base salary", "Statutory deduction"], a: 1 },
        { q: "Attrition rate refers to:", options: ["The rate at which employees leave the organization", "The hiring rate", "The promotion rate", "The accident rate"], a: 0 },
        { q: "Grievance refers to:", options: ["A formal complaint by an employee regarding workplace issues", "A customer complaint", "A legal lawsuit by a competitor", "A management directive"], a: 0 },
        { q: "A 'Red Circle' rate in compensation means an employee is:", options: ["Paid below the minimum of their pay grade", "Paid above the maximum of their pay grade", "Working in a dangerous area", "About to be fired"], a: 1 },
        { q: "Outplacement services are provided to:", options: ["New hires", "Employees being laid off to help them find new jobs", "Customers", "Competitors"], a: 1 },
        { q: "A 'Golden Parachute' is a:", options: ["Safety equipment for factory workers", "Large financial package given to executives upon termination/takeover", "Retirement gift", "Bonus for lowest performing staff"], a: 1 },
        { q: "Job enrichment is based on the theory of:", options: ["Frederick Taylor", "Frederick Herzberg (Two-Factor Theory)", "Abraham Maslow", "B.F. Skinner"], a: 1 },
        { q: "In HRM, an Assessment Center is used for:", options: ["Storing employee files", "Evaluating candidates through a series of exercises and simulations", "Medical testing", "Payroll processing"], a: 1 },
        { q: "A competency model defines:", options: ["The maximum salary", "The specific skills, knowledge, and behaviors required for success", "The company's legal structure", "The office floor plan"], a: 1 },
        { q: "An exit interview is conducted to:", options: ["Understand why an employee is leaving the organization", "Assess a candidate for a new job", "Evaluate annual performance", "Plan a retirement party"], a: 0 }
    ],
    "Business Communication": [
        { q: "Non-verbal communication accounts for approximately what percentage of meaning in face-to-face interactions?", options: ["10-20%", "30-40%", "60-90%", "100%"], a: 2 },
        { q: "Paralanguage includes:", options: ["Hand gestures", "Tone of voice, pitch, and speed", "Eye contact", "Facial expressions"], a: 1 },
        { q: "Chronemics is the study of:", options: ["Space", "Touch", "Time in communication", "Body language"], a: 2 },
        { q: "Haptics refers to communication through:", options: ["Eye contact", "Touch", "Distance", "Time"], a: 1 },
        { q: "A memo is primarily used for:", options: ["External advertising", "Internal organizational communication", "Applying for a job", "Legal contracts"], a: 1 },
        { q: "The 'You' attitude in business writing focuses on:", options: ["The writer's needs", "The reader's needs and perspectives", "The company's profits", "Criticizing the reader"], a: 1 },
        { q: "Jargon is:", options: ["A type of formal report", "Specialized terminology understood only by a specific group", "A communication barrier caused by noise", "A greeting in emails"], a: 1 },
        { q: "Which of these is a physical barrier to communication?", options: ["Different languages", "Prejudice", "Loud background noise", "Lack of motivation"], a: 2 },
        { q: "A circular is meant for:", options: ["One specific person", "Mass distribution within or outside the organization", "Confidential matters only", "Government officials only"], a: 1 },
        { q: "Minutes of a meeting represent:", options: ["The agenda", "An official written record of what was discussed and decided", "The time it took to conduct the meeting", "A list of invitees"], a: 1 },
        { q: "A presentation's effectiveness is most enhanced by:", options: ["Reading directly from slides", "Avoiding eye contact", "Using visual aids and engaging storytelling", "Speaking in a monotone voice"], a: 2 },
        { q: "The subject line of a business email should be:", options: ["Left blank", "A one-word greeting", "Clear, concise, and indicative of the email's content", "A long paragraph"], a: 2 },
        { q: "Downward communication flows from:", options: ["Subordinates to superiors", "Superiors to subordinates", "Peers to peers", "Customers to the company"], a: 1 },
        { q: "Horizontal communication occurs between:", options: ["A manager and an intern", "Employees at the same hierarchical level", "The CEO and the board", "A company and its suppliers"], a: 1 },
        { q: "An abstract in a formal report is:", options: ["A creative drawing", "A brief summary of the entire report", "The bibliography", "The appendix"], a: 1 },
        { q: "Empathy in communication means:", options: ["Feeling sorry for someone", "Understanding and sharing the feelings of another", "Interrupting with solutions", "Agreeing with everything"], a: 1 },
        { q: "A press release is used to:", options: ["Fire an employee", "Communicate newsworthy company information to the media", "Request a bank loan", "Order office supplies"], a: 1 },
        { q: "Ethnocentrism can be a barrier in:", options: ["Intrapersonal communication", "Cross-cultural communication", "Technical writing", "Accounting reports"], a: 1 },
        { q: "Which format is standard for a formal business letter?", options: ["Block format", "Circle format", "Triangle format", "Random format"], a: 0 },
        { q: "Decoding is the process where:", options: ["The sender creates the message", "The receiver interprets the message", "The message travels through a channel", "Noise disrupts the signal"], a: 1 }
    ],
    "Information Technology Management": [
        { q: "An Intranet is a network that is:", options: ["Open to the global public", "A private network accessible only to an organization's staff", "A network connecting multiple rival companies", "A government spy network"], a: 1 },
        { q: "An Extranet differs from an Intranet by:", options: ["Being completely public", "Allowing controlled access to authorized external partners/clients", "Using no internet protocols", "Being much slower"], a: 1 },
        { q: "Phishing is a cyber attack that involves:", options: ["Installing physical bugs in an office", "Deceptive emails designed to steal sensitive information", "Overloading a server with traffic", "Stealing computer hardware"], a: 1 },
        { q: "A DDoS attack stands for:", options: ["Direct Data Order System", "Distributed Denial of Service", "Digital Document Output Stream", "Data Download Open Source"], a: 1 },
        { q: "Cloud computing model IaaS stands for:", options: ["Information as a System", "Infrastructure as a Service", "Integration as a Software", "Internet as a Server"], a: 1 },
        { q: "In databases, a Primary Key is used to:", options: ["Encrypt data", "Uniquely identify each record in a table", "Sort data alphabetically only", "Connect to the internet"], a: 1 },
        { q: "SQL stands for:", options: ["Standard Query Language", "Structured Query Language", "Simple Question Language", "System Quality Logic"], a: 1 },
        { q: "An ERP system's main advantage is:", options: ["It is completely free", "It integrates various business processes into a single unified system", "It requires no training", "It only manages human resources"], a: 1 },
        { q: "The 'Internet of Things' (IoT) refers to:", options: ["A social media platform", "A network of physical objects embedded with sensors connected to the internet", "Cloud storage limits", "E-commerce websites"], a: 1 },
        { q: "Data Warehousing involves:", options: ["Storing physical paper files", "Centralizing large amounts of historical data for analysis and reporting", "Real-time transaction processing", "Deleting old data"], a: 1 },
        { q: "Ransomware is a type of malware that:", options: ["Displays unwanted ads", "Encrypts a victim's files and demands payment for the decryption key", "Steals passwords silently", "Uses the computer to mine cryptocurrency"], a: 1 },
        { q: "A VPN (Virtual Private Network) is used to:", options: ["Create a secure, encrypted connection over a less secure network", "Block all internet access", "Speed up download times", "Store physical backups"], a: 0 },
        { q: "Machine Learning is a subset of:", options: ["Cloud Computing", "Artificial Intelligence (AI)", "Blockchain", "Virtual Reality"], a: 1 },
        { q: "Agile methodology in software development focuses on:", options: ["Strict, unchangeable long-term plans", "Iterative development, collaboration, and flexibility", "Creating massive documentation first", "Solo programming without testing"], a: 1 },
        { q: "A firewall can be implemented as:", options: ["Hardware only", "Software only", "Hardware or software", "Neither"], a: 2 },
        { q: "CRM systems primarily help businesses:", options: ["Manage supply chains", "Improve customer relationships, retention, and sales", "Calculate employee payroll", "Manage factory machinery"], a: 1 },
        { q: "Open-source software means:", options: ["It is illegal to use", "The source code is freely available to view, modify, and distribute", "It can only be used by one company", "It has no bugs"], a: 1 },
        { q: "Big Data is often characterized by the 3 Vs:", options: ["Value, Vision, Validity", "Volume, Velocity, Variety", "Virtual, Visual, Vocal", "Vector, Variable, Variance"], a: 1 },
        { q: "An IP address is used to:", options: ["Identify a specific network device on the internet", "Protect against viruses", "Increase battery life", "Store passwords securely"], a: 0 },
        { q: "A GUI stands for:", options: ["Global User Internet", "Graphical User Interface", "General Utility Integration", "Great User Interaction"], a: 1 }
    ]
};
