module.exports = {
    "Organisation Effectiveness and Change": [
        { q: "Organizational effectiveness is best defined as:", options: ["Maximizing profits only", "The degree to which an organization achieves its goals efficiently", "Minimizing employee turnover", "Eliminating competition"], a: 1 },
        { q: "Which model of organizational effectiveness focuses on acquiring resources from the environment?", options: ["Goal-attainment model", "System resource model", "Internal process model", "Strategic constituencies model"], a: 1 },
        { q: "The strategic constituencies model evaluates effectiveness based on:", options: ["Profit margins", "Internal harmony", "Satisfaction of key stakeholders (customers, investors, employees)", "Speed of production"], a: 2 },
        { q: "Organizational change driven by external forces is called:", options: ["Proactive change", "Reactive change", "Incremental change", "Planned change"], a: 1 },
        { q: "According to Kotler's 8-Step Change Model, the first step is:", options: ["Create a vision", "Form a guiding coalition", "Create a sense of urgency", "Empower action"], a: 2 },
        { q: "Resistance to change is usually caused by:", options: ["Desire for new skills", "Fear of the unknown and loss of security", "Boredom", "High salary"], a: 1 },
        { q: "A 'Change Agent' is:", options: ["A software program", "A person who acts as a catalyst and assumes responsibility for managing change activities", "A competitor", "A government regulator"], a: 1 },
        { q: "Action Research in organizational development involves:", options: ["Data gathering, analysis, and collaborative problem-solving", "Only reading academic papers", "Firing employees", "Outsourcing HR"], a: 0 },
        { q: "Organizational Development (OD) is a:", options: ["Quick fix for low sales", "Long-term, planned effort to improve an organization's problem-solving and renewal processes", "Legal process", "Marketing campaign"], a: 1 },
        { q: "Sensitivity training (T-groups) aims to:", options: ["Teach technical skills", "Increase self-awareness and understanding of group dynamics", "Test physical endurance", "Improve typing speed"], a: 1 },
        { q: "Appreciative Inquiry focuses on:", options: ["Finding out who made a mistake", "Identifying and building on an organization's core strengths and what works well", "Financial audits", "Customer complaints"], a: 1 },
        { q: "Which of the following is an internal force for change?", options: ["New technology", "Economic recession", "Changes in leadership or strategy", "Government legislation"], a: 2 },
        { q: "The 'unfreezing' stage in Lewin's model involves:", options: ["Locking in new behaviors", "Breaking down the existing status quo and preparing for change", "Implementing the actual change", "Hiring new staff"], a: 1 },
        { q: "Normative-reeducative strategies for change rely on:", options: ["Using power and sanctions", "Providing rational information", "Altering social norms and values", "Ignoring the problem"], a: 2 },
        { q: "A learning organization emphasizes:", options: ["Strict hierarchies", "Continuous learning, adaptation, and knowledge sharing", "Blaming individuals for errors", "Following outdated manuals"], a: 1 },
        { q: "Total Quality Management (TQM) is an example of:", options: ["Discontinuous change", "Continuous, incremental change", "A marketing strategy", "A financial tool"], a: 1 },
        { q: "Organizational culture acts as:", options: ["A physical barrier", "A form of social control that guides employee behavior", "A financial liability", "A marketing gimmick"], a: 1 },
        { q: "Which intervention is used to improve relationships between different groups?", options: ["Job enrichment", "Intergroup team building", "Role playing", "Performance appraisal"], a: 1 },
        { q: "A 'burning platform' in change management refers to:", options: ["A literal fire", "A compelling reason or crisis that makes change absolutely necessary", "An IT failure", "A successful project"], a: 1 },
        { q: "In change management, communication should be:", options: ["One-way from the top", "Secretive", "Transparent, frequent, and two-way", "Only through email"], a: 2 }
    ],
    "Decision Modelling and Optimisation": [
        { q: "Linear programming assumes that relationships between variables are:", options: ["Exponential", "Quadratic", "Linear (straight line)", "Random"], a: 2 },
        { q: "The feasible region in a linear programming graphical solution is:", options: ["The area where the objective function is zero", "The set of all points that satisfy all constraints", "The point of maximum profit", "Outside the axes"], a: 1 },
        { q: "A 'shadow price' in linear programming represents:", options: ["The cost of a shadow", "The change in the objective function value for a one-unit increase in a constraint's right-hand side", "The price of the final product", "The cost of labor"], a: 1 },
        { q: "If an LP problem has multiple optimal solutions, the objective function is:", options: ["Parallel to a constraint line", "Zero", "Negative", "Non-linear"], a: 0 },
        { q: "The transportation problem is a special case of:", options: ["Queuing theory", "Linear programming", "Decision trees", "Markov analysis"], a: 1 },
        { q: "In the transportation problem, the objective is usually to:", options: ["Maximize distance", "Minimize total transportation cost", "Maximize inventory", "Minimize quality"], a: 1 },
        { q: "The assignment problem ensures that:", options: ["One task is assigned to multiple machines", "Each task is assigned to exactly one resource to minimize cost/time", "No tasks are completed", "All costs are equal"], a: 1 },
        { q: "The Hungarian method is an algorithm used to solve:", options: ["Linear programming", "Transportation problems", "Assignment problems", "Game theory"], a: 2 },
        { q: "In decision theory, 'Maximin' is a strategy for a:", options: ["Risk-taker", "Pessimistic decision-maker (maximize the minimum payoff)", "Optimistic decision-maker", "Neutral decision-maker"], a: 1 },
        { q: "The 'Maximax' criterion is associated with:", options: ["Minimizing loss", "An optimistic approach (maximize the maximum payoff)", "Regret", "Certainty"], a: 1 },
        { q: "Expected Value of Perfect Information (EVPI) is:", options: ["The cost of market research", "The maximum amount a decision-maker would pay for perfect knowledge of the future state", "Always zero", "The total profit"], a: 1 },
        { q: "A decision tree uses squares to represent:", options: ["Chance nodes", "Decision nodes", "End outcomes", "Probabilities"], a: 1 },
        { q: "In a decision tree, circles represent:", options: ["Decisions", "Chance events (states of nature)", "Costs", "Profits"], a: 1 },
        { q: "Game theory analyzes:", options: ["Board games only", "Strategic interactions where outcomes depend on the choices of all participants", "Single-person decisions", "Inventory levels"], a: 1 },
        { q: "A 'zero-sum game' means:", options: ["Nobody wins", "One player's gain is exactly equal to the other player's loss", "Profits are zero", "The game ends in a tie"], a: 1 },
        { q: "A Nash Equilibrium occurs when:", options: ["Everyone loses", "No player can improve their payoff by unilaterally changing their strategy", "Cooperation is perfect", "The game is over"], a: 1 },
        { q: "In Queuing theory, 'FIFO' stands for:", options: ["First In, First Out", "Fast In, Fast Out", "First In, Find Out", "Final In, First Out"], a: 0 },
        { q: "Kendall's notation (M/M/1) describes:", options: ["A marketing model", "A queuing system (Arrival/Service/Servers)", "A financial ratio", "An inventory model"], a: 1 },
        { q: "Simulation is best used when:", options: ["The problem is simple and linear", "Mathematical optimization is too complex or impossible due to randomness", "You have no data", "You want an exact optimal answer"], a: 1 },
        { q: "Monte Carlo simulation uses:", options: ["Cards", "Random number generation to model uncertainty", "Linear equations", "Historical averages only"], a: 1 }
    ],
    "Economic Environment of Business": [
        { q: "Macroeconomics focuses on:", options: ["Individual consumer choices", "Firm-level pricing", "Economy-wide phenomena like inflation, unemployment, and GDP", "Specific industry analysis"], a: 2 },
        { q: "GDP (Gross Domestic Product) is:", options: ["The total value of all stocks in a country", "The total market value of all final goods and services produced within a country in a given period", "The total exports of a country", "The average income of citizens"], a: 1 },
        { q: "Inflation is defined as:", options: ["A decrease in prices", "A sustained increase in the general price level of goods and services", "An increase in wages only", "A stagnant economy"], a: 1 },
        { q: "Monetary policy is controlled by:", options: ["The Central Bank (e.g., RBI in India)", "The Ministry of Finance", "The Prime Minister", "Commercial Banks"], a: 0 },
        { q: "Fiscal policy deals with:", options: ["Interest rates", "Money supply", "Government spending and taxation", "Exchange rates"], a: 2 },
        { q: "A budget deficit occurs when:", options: ["Government revenue exceeds expenditure", "Government expenditure exceeds revenue", "Exports exceed imports", "Imports exceed exports"], a: 1 },
        { q: "Foreign Direct Investment (FDI) in retail in India is governed by:", options: ["SEBI", "RBI and DIPP (FEMA regulations)", "Ministry of Agriculture", "Local municipalities"], a: 1 },
        { q: "A floating exchange rate is determined by:", options: ["The government", "The central bank", "Market forces of supply and demand for the currency", "The IMF"], a: 2 },
        { q: "The Balance of Payments (BOP) is:", options: ["A bank statement", "A systematic record of all economic transactions between a country and the rest of the world", "The government budget", "A company's balance sheet"], a: 1 },
        { q: "Which of the following is part of the Current Account in BOP?", options: ["FDI", "Foreign portfolio investment", "Trade in goods and services (Exports/Imports)", "External commercial borrowings"], a: 2 },
        { q: "Stagflation is a situation characterized by:", options: ["High economic growth and low inflation", "High inflation combined with high unemployment and stagnant demand", "Deflation and low unemployment", "Rapid GDP growth"], a: 1 },
        { q: "The CRR (Cash Reserve Ratio) is:", options: ["The interest rate on loans", "The percentage of deposits commercial banks must keep with the central bank", "The tax rate on cash withdrawals", "The ratio of cash to gold"], a: 1 },
        { q: "If the RBI increases the Repo Rate, it aims to:", options: ["Increase inflation", "Make borrowing cheaper", "Control inflation by making borrowing more expensive", "Increase money supply"], a: 2 },
        { q: "Economic liberalization in India began comprehensively in which year?", options: ["1947", "1971", "1991", "2014"], a: 2 },
        { q: "The 'Make in India' initiative primarily focuses on:", options: ["Importing foreign goods", "Boosting the manufacturing sector and attracting FDI", "Subsidizing agriculture", "Exporting raw materials"], a: 1 },
        { q: "A mixed economy features:", options: ["Only government control", "Only private enterprise", "A combination of private enterprise and state control/planning", "No trade with other nations"], a: 2 },
        { q: "NITI Aayog replaced which institution in India?", options: ["Finance Commission", "Reserve Bank of India", "Planning Commission", "SEBI"], a: 2 },
        { q: "GST (Goods and Services Tax) is an example of:", options: ["Direct Tax", "Indirect Tax", "Corporate Tax", "Wealth Tax"], a: 1 },
        { q: "The Business Cycle consists of:", options: ["Spring, Summer, Autumn, Winter", "Expansion, Peak, Contraction (Recession), Trough", "Inflation, Deflation, Stagflation, Hyperinflation", "Primary, Secondary, Tertiary sectors"], a: 1 },
        { q: "WPI in India stands for:", options: ["World Price Index", "Wholesale Price Index (a measure of inflation)", "Wage and Price Indicator", "Wealth Profit Index"], a: 1 }
    ],
    "Corporate Finance": [
        { q: "The primary goal of financial management is to:", options: ["Maximize profits in the short term", "Maximize shareholder wealth (firm value)", "Minimize taxes", "Increase market share"], a: 1 },
        { q: "Capital Budgeting involves decisions regarding:", options: ["Day-to-day cash management", "Long-term investments in fixed assets/projects", "Dividend payouts", "Raising equity"], a: 1 },
        { q: "Net Present Value (NPV) is calculated as:", options: ["Total cash inflows minus outflows", "Present value of cash inflows minus present value of cash outflows", "Profit divided by investment", "Revenues minus expenses"], a: 1 },
        { q: "If a project's NPV is positive, the project should generally be:", options: ["Rejected", "Accepted", "Put on hold", "Re-evaluated"], a: 1 },
        { q: "Internal Rate of Return (IRR) is the discount rate that makes:", options: ["NPV equal to zero", "NPV greater than zero", "Profit margin 10%", "Payback period 1 year"], a: 0 },
        { q: "The Payback Period measures:", options: ["Total profit over the project life", "The time required to recover the initial investment", "The accounting rate of return", "The discounted cash flows"], a: 1 },
        { q: "Cost of Capital represents:", options: ["The interest paid on a loan", "The minimum required rate of return on investments to maintain firm value", "The cost to manufacture a product", "The dividend paid per share"], a: 1 },
        { q: "WACC stands for:", options: ["Weighted Average Cost of Capital", "Working Assets Capital Cost", "Wealth Allocation and Capital Control", "Weighted Annual Cash Cycle"], a: 0 },
        { q: "According to the Modigliani-Miller theorem (without taxes), firm value is:", options: ["Determined solely by debt", "Independent of its capital structure", "Maximized with 100% debt", "Maximized with 100% equity"], a: 1 },
        { q: "Financial Leverage is the use of:", options: ["Fixed-cost sources of finance (like debt) to magnify returns to equity", "Variable-cost labor", "Equity only", "Operating assets"], a: 0 },
        { q: "Operating Leverage involves the use of:", options: ["Debt", "Equity", "Fixed operating costs", "Variable operating costs"], a: 2 },
        { q: "Working Capital Management focuses on:", options: ["Long-term investments", "Managing current assets and current liabilities", "Issuing bonds", "Mergers and acquisitions"], a: 1 },
        { q: "The formula for Net Working Capital is:", options: ["Current Assets + Current Liabilities", "Total Assets - Total Liabilities", "Current Assets - Current Liabilities", "Cash + Inventory"], a: 2 },
        { q: "The Cash Conversion Cycle measures:", options: ["The time to manufacture a product", "The time between paying for raw materials and collecting cash from sales", "The time to get a bank loan", "The time to pay dividends"], a: 1 },
        { q: "A stock dividend (bonus shares) results in:", options: ["Cash leaving the firm", "An increase in the number of shares outstanding without cash leaving the firm", "A decrease in total equity", "An increase in debt"], a: 1 },
        { q: "Gordon's Dividend Growth Model implies that dividend policy:", options: ["Is irrelevant", "Affects the value of the firm", "Only matters for tax purposes", "Is determined by the government"], a: 1 },
        { q: "Which source of finance typically has the lowest cost?", options: ["Equity shares", "Preference shares", "Debt (due to tax shield)", "Retained earnings"], a: 2 },
        { q: "Capital rationing occurs when a firm:", options: ["Has unlimited funds", "Has more acceptable projects than funds available to finance them", "Rejects all projects", "Issues too much equity"], a: 1 },
        { q: "Systematic risk in a portfolio:", options: ["Can be eliminated by diversification", "Cannot be eliminated by diversification (market risk)", "Only affects one company", "Is caused by bad management"], a: 1 },
        { q: "Beta measures a stock's:", options: ["Total risk", "Unsystematic risk", "Volatility relative to the overall market (Systematic risk)", "Dividend yield"], a: 2 }
    ],
    "Management Accounting": [
        { q: "Management accounting is primarily designed for:", options: ["External investors", "Tax authorities", "Internal managers for decision-making", "Government regulators"], a: 2 },
        { q: "Unlike financial accounting, management accounting is:", options: ["Bound by GAAP/IFRS", "Mandatory by law", "Future-oriented and not bound by strict standards", "Focused entirely on historical data"], a: 2 },
        { q: "A cost that changes in total in direct proportion to changes in volume is a:", options: ["Fixed cost", "Variable cost", "Mixed cost", "Sunk cost"], a: 1 },
        { q: "Contribution margin is calculated as:", options: ["Sales - Fixed Costs", "Sales - Variable Costs", "Sales - Net Profit", "Gross Profit - Operating Expenses"], a: 1 },
        { q: "The Break-Even Point is where:", options: ["Total Revenue = Total Variable Costs", "Total Revenue = Total Costs (Zero Profit)", "Contribution Margin = Zero", "Fixed Costs = Variable Costs"], a: 1 },
        { q: "Margin of Safety is:", options: ["The distance between the factory and the road", "Actual sales minus break-even sales", "Total fixed costs", "Total variable costs"], a: 1 },
        { q: "Relevant costs for decision-making are:", options: ["Sunk costs", "Historical costs", "Future costs that differ among alternatives", "Allocated fixed overheads"], a: 2 },
        { q: "Opportunity cost in management accounting is:", options: ["The cost of accounting software", "The benefit foregone by choosing one alternative over another", "A direct material cost", "A sunk cost"], a: 1 },
        { q: "Activity-Based Costing (ABC) allocates overhead based on:", options: ["Only direct labor hours", "Only machine hours", "Activities that drive costs", "Total sales revenue"], a: 2 },
        { q: "A master budget typically begins with the preparation of the:", options: ["Production budget", "Cash budget", "Sales budget", "Capital budget"], a: 2 },
        { q: "A flexible budget is:", options: ["A budget that changes based on management's mood", "A budget adjusted for different levels of actual activity/volume", "A budget for fixed costs only", "A budget with no limits"], a: 1 },
        { q: "Standard costing involves:", options: ["Using historical costs only", "Establishing predetermined costs for products and comparing them to actual costs", "Ignoring variances", "Using competitor's costs"], a: 1 },
        { q: "A variance is favorable when:", options: ["Actual cost exceeds standard cost", "Actual revenue is less than standard revenue", "Actual cost is less than standard cost", "Standard cost is zero"], a: 2 },
        { q: "Responsibility accounting focuses on:", options: ["Assigning costs and revenues to the manager responsible for them", "Blaming employees for external market drops", "Filing tax returns", "Reporting to shareholders"], a: 0 },
        { q: "A cost center manager is responsible for:", options: ["Revenues and costs", "Investments", "Costs only", "Profits only"], a: 2 },
        { q: "Transfer pricing refers to:", options: ["The price charged to external customers", "The price charged when one division sells goods/services to another division of the same company", "The cost of transporting goods", "The price of competitors' products"], a: 1 },
        { q: "Make or buy decisions rely primarily on:", options: ["Total fixed costs", "Comparing relevant internal manufacturing costs against external purchase price", "Sunk costs", "Allocated corporate overhead"], a: 1 },
        { q: "Zero-Based Budgeting (ZBB) requires managers to:", options: ["Use last year's budget plus 5%", "Justify every expense from scratch for each new period", "Budget only for zero-profit projects", "Ignore all fixed costs"], a: 1 },
        { q: "Return on Investment (ROI) for an investment center is calculated as:", options: ["Sales / Assets", "Operating Income / Average Operating Assets", "Net Profit / Equity", "Gross Margin / Sales"], a: 1 },
        { q: "The Balanced Scorecard includes which four perspectives?", options: ["Financial, Customer, Internal Process, Learning & Growth", "Sales, Marketing, HR, Finance", "Short-term, Long-term, Medium-term, Past", "Assets, Liabilities, Equity, Revenue"], a: 0 }
    ],
    "Production and Operations Management": [
        { q: "Operations Management involves the transformation of:", options: ["Data into reports", "Inputs (materials, labor) into outputs (goods, services)", "Cash into inventory", "Employees into managers"], a: 1 },
        { q: "Which layout is best suited for mass production of a single standardized product?", options: ["Process layout", "Fixed-position layout", "Product layout (Assembly line)", "Cellular layout"], a: 2 },
        { q: "A process layout is arranged by:", options: ["The sequence of operations", "Grouping similar machines or functions together (e.g., all welding in one area)", "The physical location of a large product (e.g., ship)", "Color of the product"], a: 1 },
        { q: "Takt time is:", options: ["The time it takes to set up a machine", "The rate at which products must be produced to meet customer demand", "The transit time", "The time a worker takes a break"], a: 1 },
        { q: "Just-In-Time (JIT) production focuses on:", options: ["Maximizing inventory to avoid stockouts", "Eliminating waste and reducing inventory by producing only what is needed when needed", "Producing large batches", "Using the cheapest materials"], a: 1 },
        { q: "Kanban is a visual signal used in:", options: ["Push systems", "Pull systems (JIT) to trigger production or movement of parts", "Quality control charts", "Employee attendance"], a: 1 },
        { q: "MRP (Material Requirements Planning) is driven by:", options: ["The Master Production Schedule (MPS)", "Random estimates", "Competitor actions", "Marketing budget"], a: 0 },
        { q: "The Economic Order Quantity (EOQ) model seeks to minimize:", options: ["Holding costs only", "Ordering costs only", "The sum of holding and ordering costs", "Production time"], a: 2 },
        { q: "In EOQ, if ordering cost increases, the optimal order quantity:", options: ["Decreases", "Increases", "Remains the same", "Becomes zero"], a: 1 },
        { q: "ABC analysis in inventory management classifies items based on:", options: ["Alphabetical order", "Weight", "Annual usage value (A=High, B=Medium, C=Low value)", "Color"], a: 2 },
        { q: "Six Sigma aims to reduce:", options: ["Profits", "Defects and process variation", "Employee salaries", "Inventory exclusively"], a: 1 },
        { q: "A defect rate in Six Sigma corresponds to:", options: ["3.4 defects per million opportunities", "1 defect per hundred", "0 defects", "10 defects per million"], a: 0 },
        { q: "Which chart is used in statistical process control to monitor sample means?", options: ["Gantt Chart", "Pareto Chart", "X-bar chart (Control chart)", "Pie chart"], a: 2 },
        { q: "The Pareto Principle (80/20 rule) in quality management suggests:", options: ["80% of problems are caused by 20% of causes", "80% of products are defective", "20% of employees do 80% of work", "80% of customers complain"], a: 0 },
        { q: "A Gantt chart is primarily used for:", options: ["Inventory tracking", "Project scheduling and tracking progress over time", "Quality control", "Financial accounting"], a: 1 },
        { q: "CPM (Critical Path Method) is used to:", options: ["Calculate costs", "Identify the longest sequence of dependent tasks that determines project duration", "Manage customer complaints", "Design products"], a: 1 },
        { q: "Slack time on the critical path is:", options: ["Negative", "Zero", "Positive", "Infinite"], a: 1 },
        { q: "Kaizen translates to:", options: ["Mass production", "Continuous improvement", "Zero defects", "Large batch size"], a: 1 },
        { q: "Poka-yoke means:", options: ["Fast delivery", "Mistake-proofing or fail-safing a process", "Quality inspection", "Inventory counting"], a: 1 },
        { q: "Capacity planning ensures that:", options: ["The factory looks good", "The organization has the appropriate level of resources to meet demand", "Marketing budget is spent", "Taxes are paid"], a: 1 }
    ],
    "Marketing Research": [
        { q: "The primary purpose of marketing research is to:", options: ["Create advertisements", "Provide information to reduce uncertainty in marketing decisions", "Sell products directly", "Train sales staff"], a: 1 },
        { q: "Secondary data is:", options: ["Data collected first-hand for the specific research problem", "Data that was previously collected by someone else for another purpose", "Data collected in the second phase of research", "Always quantitative"], a: 1 },
        { q: "Primary data collection methods include:", options: ["Reading census reports", "Searching online databases", "Surveys, interviews, and observations", "Reviewing company financial records"], a: 2 },
        { q: "Exploratory research is used when:", options: ["The problem is well-defined", "The problem is ambiguous and researchers need to gain insights and ideas", "Testing specific hypotheses", "Determining cause-and-effect"], a: 1 },
        { q: "Causal research relies heavily on:", options: ["Focus groups", "Observation", "Experiments", "Secondary data"], a: 2 },
        { q: "A focus group is an example of:", options: ["Quantitative research", "Qualitative research", "Experimental research", "Secondary research"], a: 1 },
        { q: "In a probability sample:", options: ["Only volunteers are selected", "Every member of the population has a known, non-zero chance of being selected", "The researcher chooses whoever is convenient", "Sample size doesn't matter"], a: 1 },
        { q: "Which is a non-probability sampling method?", options: ["Simple random sampling", "Stratified sampling", "Convenience sampling", "Cluster sampling"], a: 2 },
        { q: "A Likert scale typically asks respondents to indicate their:", options: ["Income level", "Age", "Level of agreement or disagreement with a statement", "Favorite brand"], a: 2 },
        { q: "Semantic differential scales use:", options: ["Only numbers", "Bipolar adjectives (e.g., Good---Bad)", "Multiple choice options", "Open-ended questions"], a: 1 },
        { q: "Open-ended questions are useful for:", options: ["Getting standardized data for easy statistical analysis", "Getting rich, detailed, and unanticipated insights", "Saving time during analysis", "Telephone surveys with limited time"], a: 1 },
        { q: "A leading question is problematic because it:", options: ["Is too short", "Directs or suggests the desired answer to the respondent", "Is placed at the end of the survey", "Uses simple vocabulary"], a: 1 },
        { q: "Cross-tabulation is used to:", options: ["Delete missing data", "Analyze the relationship between two or more categorical variables", "Calculate standard deviation", "Write the final report"], a: 1 },
        { q: "Reliability in marketing research refers to:", options: ["Whether the survey measures what it intends to measure", "The consistency and repeatability of the measurement", "The cost of the research", "The speed of data collection"], a: 1 },
        { q: "Validity in marketing research refers to:", options: ["Getting the same result twice", "The accuracy of the measurement (measuring what it's supposed to measure)", "The sample size", "The formatting of the questionnaire"], a: 1 },
        { q: "A test market is used to:", options: ["Evaluate employee performance", "Test a new product or marketing mix in a small, representative real-world area before full launch", "Sell leftover inventory", "Conduct focus groups"], a: 1 },
        { q: "Ethnographic research involves:", options: ["Sending email surveys", "Observing consumers in their natural environment", "Analyzing website clicks", "Reviewing sales data"], a: 1 },
        { q: "Data cleaning involves:", options: ["Wiping the computer screen", "Identifying and correcting errors, inconsistencies, or missing values in the dataset", "Deleting all negative responses", "Formatting the report"], a: 1 },
        { q: "Factor analysis is a statistical technique used to:", options: ["Increase the number of variables", "Reduce a large number of variables into a fewer number of underlying factors", "Calculate the mean", "Determine sample size"], a: 1 },
        { q: "Cluster analysis in marketing is often used for:", options: ["Pricing products", "Market segmentation (grouping similar consumers together)", "Advertising copy testing", "Inventory management"], a: 1 }
    ],
    "Management of Information Systems": [
        { q: "An MIS (Management Information System) is primarily designed to:", options: ["Automate factory machines", "Provide managers with information needed for decision-making and control", "Design websites", "Manage employee payroll only"], a: 1 },
        { q: "Data refers to raw facts, while Information is:", options: ["Also raw facts", "Data processed into a meaningful and useful context", "Hardware", "Software"], a: 1 },
        { q: "A Transaction Processing System (TPS) operates at which organizational level?", options: ["Strategic level", "Management level", "Operational level", "Executive level"], a: 2 },
        { q: "Executive Support Systems (ESS) are designed for:", options: ["Line workers", "Middle managers", "Senior management for strategic, unstructured decisions", "Customers"], a: 2 },
        { q: "Decision Support Systems (DSS) use:", options: ["Only historical data", "Models, data, and analytical tools to help managers make semi-structured or unstructured decisions", "Only external news", "Pre-programmed robotic movements"], a: 1 },
        { q: "The term 'SaaS' stands for:", options: ["Storage as a Service", "Software as a Service", "Security as a System", "System as a Software"], a: 1 },
        { q: "A relational database organizes data into:", options: ["A single long text file", "Two-dimensional tables (relations) with rows and columns", "A hierarchical tree structure", "Folders on a desktop"], a: 1 },
        { q: "Data Mining is the process of:", options: ["Physically digging for computer hardware", "Analyzing large pools of data to find hidden patterns and rules", "Entering data into a spreadsheet", "Deleting old data"], a: 1 },
        { q: "An ERP (Enterprise Resource Planning) system aims to:", options: ["Fragment data across departments", "Integrate data and processes of an entire organization into a single system", "Only manage human resources", "Replace the CEO"], a: 1 },
        { q: "Supply Chain Management (SCM) systems help to:", options: ["Design advertisements", "Manage the flow of products, information, and funds between suppliers, company, and customers", "Manage employee benefits", "Process accounting entries"], a: 1 },
        { q: "Knowledge Management Systems (KMS) are used to:", options: ["Calculate taxes", "Capture, store, distribute, and apply organizational knowledge and expertise", "Track delivery trucks", "Print invoices"], a: 1 },
        { q: "An Expert System (ES) is a type of AI that:", options: ["Mimics human movement", "Simulates the reasoning and decision-making of a human expert in a specific domain", "Generates images", "Plays video games"], a: 1 },
        { q: "The System Development Life Cycle (SDLC) typically starts with:", options: ["Coding", "Testing", "Systems Analysis / Planning", "Maintenance"], a: 2 },
        { q: "Prototyping in system development involves:", options: ["Writing a massive manual first", "Building a quick, preliminary model of a system for users to evaluate", "Buying off-the-shelf software", "Skipping the design phase entirely"], a: 1 },
        { q: "Outsourcing IT functions means:", options: ["Hiring more internal IT staff", "Contracting external vendors to manage IT operations or development", "Moving servers to the basement", "Selling the company"], a: 1 },
        { q: "A Denial of Service (DoS) attack aims to:", options: ["Steal passwords", "Crash a network or website by overwhelming it with traffic", "Encrypt data for ransom", "Install spyware"], a: 1 },
        { q: "Encryption is the process of:", options: ["Translating encoded text into readable text", "Converting readable data into an unreadable format to prevent unauthorized access", "Deleting files securely", "Compressing files to save space"], a: 1 },
        { q: "Disaster Recovery Planning focuses on:", options: ["Marketing after a bad PR event", "Restoring IT systems and data after a disruption or disaster", "Financial bankruptcy", "Employee resignation"], a: 1 },
        { q: "E-commerce model B2B stands for:", options: ["Business to Bank", "Business to Business", "Buyer to Buyer", "Brand to Brand"], a: 1 },
        { q: "Business Intelligence (BI) tools are used for:", options: ["Corporate espionage", "Analyzing data to present actionable information to help executives make business decisions", "Writing code", "Designing logos"], a: 1 }
    ]
};
